import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/Layout/Layout";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { BagProvider } from "@/contexts/BagContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ThemeProvider>
                <BagProvider>
                    <body className={inter.className}>
                        <Layout>{children}</Layout>
                    </body>
                </BagProvider>
            </ThemeProvider>
        </html>
    );
}
